universe:
  tickers:
    - "AI.PA"
    - "AIR.PA"
    - "ALO.PA"
    - "ORA.PA"
    - "BNP.PA"
    - "ACA.PA"
    - "GLE.PA"
    - "CS.PA"
    - "EN.PA"
    - "CAP.PA"
    - "DG.PA"
    - "HO.PA"
    - "ML.PA"
    - "MC.PA"
    - "OR.PA"
    - "RI.PA"
    - "PUB.PA"
    - "VIE.PA"
    - "VIV.PA"
    - "SU.PA"
    - "DSY.PA"
    - "KER.PA"
    - "EL.PA"
    - "ENGI.PA"
    - "TTE.PA"
    - "SAF.PA"
    - "STLA.PA"
    - "BN.PA"
    - "UL.PA"
    - "SAN.PA"
    - "LR.PA"
    - "RMS.PA"
    - "FR.PA"
    - "TEP.PA"
    - "WLN.PA"
    - "CA.PA"
    - "SGO.PA"
    - "STM.PA"
    - "EDEN.PA"
    - "ERF.PA"
    - "AC.PA"
    - "ADP.PA"
    - "AF.PA"
    - "AKE.PA"
    - "ALD.PA"
    - "AMUN.PA"
    - "APAM.AS"
    - "ATE.PA"
    - "ATO.PA"
    - "BB.PA"
    - "BIM.PA"
    - "BOL.PA"
    - "BVI.PA"
    - "CARM.PA"
    - "COV.PA"
    - "CO.PA"
    - "COFA.PA"
    - "CGG.PA"
    - "DAN.PA"
    - "DEC.PA"
    - "ELIOR.PA"
    - "ENX.PA"
    - "ERA.PA"
    - "ETL.PA"
    - "FDJ.PA"
    - "FGR.PA"
    - "FNAC.PA"
    - "FRVIA.PA"
    - "GEC.PA"
    - "GET.PA"
    - "GTT.PA"
    - "ICAD.PA"
    - "ANTIN.PA"
    - "IPN.PA"
    - "IPS.PA"
    - "ITP.PA"
    - "KOF.PA"
    - "KORI.PA"
    - "LI.PA"
    - "MDM.PA"
    - "MF.PA"
    - "MMB.PA"
    - "MMT.PA"
    - "MTU.PA"
    - "NEOEN.PA"
    - "NEX.PA"
    - "NK.PA"
    - "ORP.PA"
    - "QDT.PA"
    - "RCO.PA"
    - "RUI.PA"
    - "RXL.PA"
    - "SCR.PA"
    - "SESG.PA"
    - "SK.PA"
    - "SOI.PA"
    - "SOP.PA"
    - "SPIE.PA"
    - "SW.PA"
    - "TE.PA"
    - "VANTI.PA"
    - "UBI.PA"
    - "VK.PA"
    - "VLA.PA"
    - "VLTSA.PA"
    - "VRLA.PA"
    - "VCT.PA"
    - "WAVE.PA"
  min_market_cap: 1500000000.0
  min_adv_3m: 200000.0
filters:
  max_pe_ttm: 25.0
  max_forward_pe: 15.0
  max_debt_to_equity: 0.35
  min_eps_cagr: 0.08
  min_eps_cagr_v1_1: 0.15
  max_peg: 1.2
  min_market_cap: 5000000000.0
weights:
  garp:
    valuation: 0.30
    growth: 0.30
    balance_sheet: 0.25
    size: 0.15
  nexus:
    quality: 0.65
    safety: 0.35
profile:
  name: balanced
  garp:
    pe_ttm_max: 25.0
    pe_fwd_max: 15.0
    debt_to_equity_max: 0.35
    eps_cagr_min: 0.15